name: Deploy to Koyeb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Set gradlew as executable
      run: chmod +x ./gradlew        

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Build Docker Image
      run: docker build . -t advpro-eshop:latest

    - name: Log in to Koyeb Registry
      run: echo ${{ secrets.KOYEB_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.KOYEB_REGISTRY_USERNAME }} --password-stdin registry.koyeb.com

    - name: Tag and Push Docker Image to Koyeb Registry
      run: |
        docker tag advpro-eshop:latest registry.koyeb.com/hilaldfzn/advpro-eshop:latest
        docker push registry.koyeb.com/hilaldfzn/advpro-eshop:latest

    - name: Deploy to Koyeb
      run: |
        curl -X POST https://app.koyeb.com/api/v1/services/786395a6-7417-497a-b878-d17e2ee78731/redeploy \
        -H 'Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}' \
        -H 'Content-Type: application/json' \
        --data-raw '{"image":"registry.koyeb.com/hilaldfzn/advpro-eshop:latest"}'